trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  artifactName: 'C-Build-Test-$(Build.BuildId)'

steps:
- script: |
    echo "Installing CMake"
    sudo apt update
    sudo apt upgrade -y
    sudo apt install -y cmake
  displayName: 'Install dependencies'

- script: |
    echo "Configuring CMake"
    cmake .
  displayName: 'Pre-build step'

- script: |
    echo "Building the project"
    make
  displayName: 'Build'

- script: |
    echo "Running tests"
    ctest
  displayName: 'Post-build step'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'out'
    artifact: $(artifactName)
    publishLocation: 'pipeline'
